### ISSUE TITLE
Demo.py: Negative Dimensions are Not Allowed

### ISSUE THREAD

**Issue by nauman-tintash** [laughtervv/DISN#14]
When I run the demo, it gives this error on the following line:
`extra_pts = np.zeros((1, SPLIT_SIZE * NUM_SAMPLE_POINTS - TOTAL_POINTS, 3), dtype=np.float32)`

The split size comes out to be 80, NUM_SAMPLE_POINTS is 212182 and TOTAL_POINTS is 16974593.

Where are these numbers coming from and why could this error be coming up?

**Comment by Xharlie** [comment]
hi this error is due to python 2 and 3, please adjust accordingly.

**Comment by nauman-tintash** [comment]
Switching to python3 resolved this issue. Thanks.
